if(ZE_USE_GTSAM)
  find_package(gtsam_catkin REQUIRED)
  message(STATUS "GTSAM headers: ${GTSAM_INCLUDE_DIR}")
  message(STATUS "GTSAM (gtsam_catkin) found.")
  message(STATUS "GTSAM (gtsam_catkin) libraries: ${gtsam_catkin_LIBRARIES}.")
  message(STATUS "GTSAM (gtsam_catkin) headers: ${gtsam_catkin_INCLUDE_DIRS}.")
  list(APPEND catkin_LIBRARIES  ${gtsam_catkin_LIBRARIES})
  list(APPEND INCLUDE_DIRS ${GTSAM_INCLUDE_DIR})
  list(APPEND INCLUDE_DIRS ${gtsam_catkin_INCLUDE_DIRS})
  include_directories(${INCLUDE_DIRS})
endif()