option(ZE_SINGLE_PRECISION_FLOAT "Compile with single precision float" OFF)
option(ZE_USE_BRISK "Compile with BRISK" OFF)
option(ZE_USE_OPENCV "Compile with OPENCV" ON)
option(ZE_USE_GTSAM "Compile with GTSAM" ON)
option(ZE_USE_ARRAYFIRE "Compile ArrayFire and IMP wrapper" OFF)
option(ZE_DETERMINISTIC "Use deterministic random numbers" ON)
option(ZE_VIO_LIMITED "Limited functionality in VIO" OFF)